# Generated by Django 5.0.4 on 2024-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0003_airport_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
