# Generated by Django 5.0.4 on 2024-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0004_flight_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="arrivalTime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departureTime",
            field=models.DateTimeField(),
        ),
    ]
