# Generated by Django 5.0.4 on 2024-05-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0007_flight_airline"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
