# Generated by Django 5.0.4 on 2024-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0009_flight_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="plane",
            name="seatConfiguration",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
