# Generated by Django 5.0.4 on 2024-05-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0002_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="budget",
            field=models.IntegerField(default=0),
        ),
    ]
