# Generated by Django 5.0.4 on 2024-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tasks", "0004_task_airport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approval",
            name="tasksToDo",
        ),
        migrations.AddField(
            model_name="approval",
            name="tasksToDoArrival",
            field=models.ManyToManyField(
                related_name="arrTasks", to="Tasks.regulartasks"
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="tasksToDoDeparture",
            field=models.ManyToManyField(
                related_name="depTasks", to="Tasks.regulartasks"
            ),
        ),
    ]
