# Generated by Django 5.0.4 on 2024-06-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tasks", "0005_remove_approval_taskstodo_approval_taskstodoarrival_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("toDo", "toDo"),
                    ("inProgress", "inProgress"),
                    ("done", "done"),
                ],
                default="inProgress",
                max_length=12,
            ),
        ),
    ]
