# Generated by Django 5.0.4 on 2024-06-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tasks", "0008_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="issue",
            field=models.CharField(
                choices=[
                    ("Wrong working hours", "Wrong working hours"),
                    ("Request coworkers change", "Request coworkers change"),
                    ("Problem with the task", "Problem with the task"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("toDo", "To Do"),
                    ("inProgress", "In Progress"),
                    ("done", "Done"),
                ],
                default="inProgress",
                max_length=12,
            ),
        ),
    ]
