# Generated by Django 5.0.4 on 2024-06-18 15:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0009_flight_status"),
        ("Tasks", "0010_report_date_report_response_report_responsedate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("toDo", "To Do"),
                    ("inProgress", "In Progress"),
                    ("done", "Done"),
                ],
                default="toDo",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="FlightReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue",
                    models.CharField(
                        choices=[
                            ("Wrong working hours", "Wrong working hours"),
                            ("Not enough fuel", "Not enough fuel"),
                            ("Problem with the task", "Problem with the task"),
                            ("Aircraft failure", "Aircraft failure"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=40,
                    ),
                ),
                ("message", models.CharField(max_length=250)),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                ("responseDate", models.DateTimeField(blank=True, null=True)),
                ("response", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Database.flight",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
