# Generated by Django 5.0.4 on 2024-06-19 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tasks", "0011_alter_task_status_flightreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=255)),
                ("date", models.DateField()),
                (
                    "fromUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "toUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PilotConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="conv_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(
                        related_name="content", to="Tasks.pilotmessage"
                    ),
                ),
            ],
        ),
    ]
