# Generated by Django 5.0.4 on 2024-06-19 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tasks", "0013_pilotmessage_answertoflight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilotmessage",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
