# Generated by Django 5.0.4 on 2024-06-20 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tasks", "0014_alter_pilotmessage_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilotmessage",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
